version: "3.3"

services:

  traefik:
    image: "traefik:v2.8"
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=egortsaryk@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  echo1:
    image: hashicorp/http-echo
    container_name: "echo-server-1"
    command: ['-text', 'This is the FIRST contaner']
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.echo1.rule=Host(`cas-nft-marketplace.deip.world`)"
      - "traefik.http.routers.echo1.entrypoints=web"
      - "traefik.http.routers.echo1.entrypoints=websecure"
      - "traefik.http.routers.echo1.tls.certresolver=myresolver"

  echo2:
    image: hashicorp/http-echo
    container_name: "echo-server-2"
    command: ['-text', 'This is the SECOND contaner']
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.echo2.rule=Host(`cas-nft-marketplace-web-server.deip.world`)"
      - "traefik.http.routers.echo2.entrypoints=web"
      - "traefik.http.routers.echo2.entrypoints=websecure"
      - "traefik.http.routers.echo2.tls.certresolver=myresolver"

volumes:
  letsencrypt:
    external: true