version: "3.3"

services:

  traefik:
    image: "traefik:v2.8"
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=egortsaryk@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  echo1:
    image: hashicorp/http-echo
    container_name: "echo-server-1"
    command: ['-text', 'This is the FIRST contaner']
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.echo1.rule=Host(`cas-nft-marketplace.deip.world`)"
      - "traefik.http.routers.echo1.entrypoints=web"
      - "traefik.http.routers.echo1.entrypoints=websecure"
      - "traefik.http.routers.echo1.tls.certresolver=myresolver"

  echo2:
    image: hashicorp/http-echo
    container_name: "echo-server-2"
    command: ['-text', 'This is the SECOND contaner']
    labels:
      # - "traefik.enable=true"
      # - "traefik.http.routers.echo2.rule=Host(`cas-nft-marketplace-web-server.deip.world`)"
      # - "traefik.http.routers.echo2.entrypoints=web"
      # - "traefik.http.routers.echo2.entrypoints=websecure"
      # - "traefik.http.routers.echo2.tls.certresolver=myresolver"


      - "traefik.enable=true"
      - "traefik.http.routers.echo2.rule=Host(`cas-nft-marketplace-web-server.deip.world`)"
      - "traefik.http.routers.echo2.entrypoints=web"
      - "traefik.http.routers.echo2.entrypoints=websecure"
      - "traefik.http.routers.echo2.service=appchain_http"

      - "traefik.http.services.appchain_http.loadbalancer.server.port=5678"
      
      
      - "traefik.http.routers.echo3.rule=Host(`cas-nft-marketplace-web-sockets-1.deip.world`)"
      - "traefik.http.routers.echo3.entrypoints=web"
      - "traefik.http.routers.echo3.entrypoints=websecure"
      - "traefik.http.routers.echo3.service=appchain_ws"

      - "traefik.http.services.appchain_ws.loadbalancer.server.port=5678"


      # - "traefik.http.routers.vscode.entrypoints=web"
      # - "traefik.http.routers.vscode.entrypoints=websecure"
      # - "traefik.vscode.backend=vscode2"
      # - "traefik.vscode.frontend.rule=Host(`cas-nft-marketplace-web-server.deip.world`)"
      # - "traefik.vscode.port=5678"

      # - "traefik.http.routers.app2.entrypoints=web"
      # - "traefik.http.routers.app2.entrypoints=websecure"
      # - "traefik.app.backend=app2"
      # - "traefik.app.frontend.rule=Host(`cas-nft-marketplace-web-sockets-1.deip.world`)"
      # - "traefik.app.port=5678"




volumes:
  letsencrypt:
    external: true