version: "3.3"

services:

  traefik:
    image: "traefik:v2.8"
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.mongodb.address=:27017"
      - "--entrypoints.ws.address=:8083"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=egortsaryk@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
      - "27017:27017"
    volumes:
      - "letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"


  substrate-node:
    image: deipworld/appchain-deip:latest
    container_name: substrate-node
    restart: always
    command: appchain-deip --dev --ws-external --rpc-external --rpc-methods=Unsafe --rpc-cors=all --base-path=/var/lib/deipd
    expose:
      - "9944"
      - "9933"
    volumes:
      - chainstorage:/var/lib/deipd
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: 2048M
        reservations:
          memory: 1024M
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.node_ws.rule=Host(`demo.appchain.ws.casimir.one`)"
      - "traefik.http.routers.node_ws.entrypoints=websecure"
      - "traefik.http.routers.node_ws.tls.certresolver=myresolver"
      - "traefik.http.routers.node_ws.service=node_ws"
      - "traefik.http.services.node_ws.loadbalancer.server.port=9944"
      
      - "traefik.http.routers.node_http.rule=Host(`demo.appchain.http.casimir.one`)"
      - "traefik.http.routers.node_http.entrypoints=websecure"
      - "traefik.http.routers.node_http.tls.certresolver=myresolver"
      - "traefik.http.routers.node_http.service=node_http"
      - "traefik.http.services.node_http.loadbalancer.server.port=9933"


  web-server:
    image: deipworld/casimir-nft-marketplace-web-server:latest
    container_name: web-server
    restart: always
    depends_on:
      - substrate-node
      - storage
    links:
      - substrate-node
      - storage
    expose:
      - "80"
      - "8083"
    environment:
      NODE_ENV: development
      PROTOCOL: 2
      PORT: 80
      WS_PORT: 8083
      DEIP_FULL_NODE_URL: https://demo.appchain.http.casimir.one
      DEIP_MONGO_STORAGE_CONNECTION_URL: mongodb://casimir:xZ6GZunKhaUzX44J@demo.casimir.one:27017/casimir-storage?authSource=admin
      CORE_ASSET: '{ "id": 0, "symbol": "DEIP", "precision": 18 }'
      CHAIN_BLOCK_INTERVAL_MILLIS: 6000
      TENANT: "6561845613164402145092105428472817005070"
      TENANT_PRIV_KEY: "1d24d7eda9803457dcea233872d513f4468d41b7a8b77555c161be1d1917330c"
      TENANT_PORTAL: '{"privKey":"1265fe9c39e665908f2d6fda3f0371d34de255e4420eb0aaa2907a8d80836d99","pubKey":"22688b484f3e0dde55bd52221fd9ba806c8af5388e02543e14fbf3a639d4d825"}'
      TENANT_HOT_WALLET: '{"privKey":"38b6bf99e4b06e64cafeeedf1f418f8f03b472e14ece7f5e5cb4d9aa9e6caef7","daoId":"20d1c50067827d1ba447d1be4a4d5129fb0583ed"}'
      TENANT_FILE_STORAGE_TYPE: 1
    volumes:
      - offchainstorage:/usr/src/app/files
      - logstorage:/usr/src/app/logs
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.webserver_http.rule=Host(`demo.webserver.http.casimir.one`)"
      - "traefik.http.routers.webserver_http.entrypoints=web"
      - "traefik.http.routers.webserver_http.tls.certresolver=myresolver"
      - "traefik.http.routers.webserver_http.service=webserver_http"
      - "traefik.http.services.webserver_http.loadbalancer.server.port=80"

      # - "traefik.http.routers.webserver_ws.rule=Host(`demo.webserver.ws.casimir.one`)"
      # - "traefik.http.routers.webserver_ws.entrypoints=web"
      # - "traefik.http.routers.webserver_ws.tls.certresolver=myresolver"
      # - "traefik.http.routers.webserver_ws.service=webserver_ws"
      # - "traefik.http.services.webserver_ws.loadbalancer.server.port=8080"

      - traefik.tcp.routers.webserver_ws.entrypoints=ws
      - traefik.tcp.routers.webserver_ws.tls=true
      - traefik.tcp.routers.webserver_ws.tls.certresolver=myresolver
      - traefik.tcp.routers.webserver_ws.rule=HostSNI(`demo.webserver.ws.casimir.one`)
      - traefik.tcp.routers.webserver_ws.tls.domains[0].main=demo.webserver.ws.casimir.one
      - traefik.tcp.routers.webserver_ws.service=webserver_ws
      - traefik.http.services.webserver_ws.loadbalancer.server.port=8083


  web-client:
    image: deipworld/casimir-nft-marketplace-web-client:latest
    container_name: web-client
    restart: always
    depends_on:
      - substrate-node
      - web-server
    links:
      - substrate-node
      - web-server
    # ports:
    #   - "8080:80"
    environment:
      NODE_ENV: development
      PROTOCOL: 2
      TENANT: "6561845613164402145092105428472817005070"
      # web server ws and http
      DEIP_SERVER_URL: https://demo.webserver.http.casimir.one
      DEIP_WEB_SOCKET_URL: wss://demo.webserver.ws.casimir.one
      # chain node
      DEIP_FULL_NODE_URL: wss://demo.appchain.ws.casimir.one
      # wallet
      WALLET_URL: https://demo.wallet.casimir.one
      TENANT_HOT_WALLET_DAO_ID: '20d1c50067827d1ba447d1be4a4d5129fb0583ed'
      CORE_ASSET: '{ "id": 0, "symbol": "DEIP", "precision": 18 }'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.webclient.rule=Host(`demo.casimir.one`)"
      - "traefik.http.routers.webclient.entrypoints=websecure"
      - "traefik.http.routers.webclient.tls.certresolver=myresolver"
      - "traefik.http.routers.webclient.service=webclient"
      - "traefik.http.services.webclient.loadbalancer.server.port=80"


  storage:
    image: mongo:3.6.5
    container_name: storage
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=casimir
      - MONGO_INITDB_ROOT_PASSWORD=xZ6GZunKhaUzX44J
    volumes: 
      - offchainstorage:/data/db
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.storage.entrypoints=mongodb"
      - "traefik.tcp.routers.storage.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.storage.tls=false"
      - "traefik.tcp.services.storage.loadbalancer.server.port=27017"
      - "traefik.tcp.routers.storage.service=storage"

      # https://stackoverflow.com/questions/71300670/how-to-setup-mongodb-with-traefik-and-docker-compose
      # https://community.traefik.io/t/tls-with-letsencrypt-for-tcp-to-mongo/4957
      # - traefik.tcp.routers.storage.tls=true
      # - traefik.tcp.routers.storage.tls.certresolver=myresolver
      # - traefik.tcp.routers.storage.rule=HostSNI(`demo.storage.casimir.one`)
      # - traefik.tcp.routers.storage.tls.domains[0].main=demo.storage.casimir.one

volumes:
  letsencrypt:
    external: true
  chainstorage:
    external: true
  offchainstorage:
    external: true
  logstorage:
    external: true
