[blockchain]
rpc = "ws://substrate-node:9944/"

[message_broker]
kafka_bootstrap_servers = "kafka:9092"

[offchain]
[offchain.last_known_block]
## Uncomment this section to be able to set last-known-block 
## for the dummy offchain-service-client
number = 21634
hash = "0x3364a0d828b52cb767c9634f33e3f9337d00f9e30e51ed92a8427ee08116879f"
parent_hash = "0xd7d82904a58cb1c267cd2a6b0d4af66f87379d157182dd43a03df6fb608fdd5c"
